* Fixed issue with setup script paths.  It didn't include 'SetupScrip…
SeattleCodeCamp/WebSite pull request #72
Opened 2017-03-11 21:27 UTC by tigewilliams

* Fixed issue with setup script paths.  It didn't include 'SetupScripts' in the path.

* Refactored to use common 'RunSetupScript' function

* Added '-recreate' command line argument to allow user to recreate the database.  This is useful if the script failed for some reason and left the database in an odd state

* Added try...catch blocks

* Refactored various functions to take a Connection object.  This allows us to properly close the connection if something goes wrong.

* Changed the query that looks for the CodeCamp database to use ExecuteNonScalar.  This way, we don't have to loop on results.  The SQL query will directly look for our database.

* Added 'DropDatabase.ps1' Powershell script.  This drops the CodeCamp database, if it exists.  Mostly just for cleanup.

2017-03-11 23:48 UTC, slobo80 requested changes

2017-03-11 23:48 UTC, slobo80 commented on DropDatabase.ps1
> +		if(!$exists)
We can remove the negation if we swap return true and return false.

2017-03-11 23:48 UTC, slobo80 commented on SetupDevMachine.ps1
> +		if(!$exists)
The same as in the other file

2017-03-13 01:24 UTC, tigewilliams commented
I updated the code to remove the negation in DbExists.  I still have it checking $exists for existence instead of just returning it directly since I'm not a huge fan of 'truthy' evaluations.  I'd rather just have explicit boolean values.

2017-03-13 02:45 UTC, slobo80 approved these changes

2017-03-13 02:45 UTC, merged